language: ruby
rvm:
  - 2.0.0
  - 1.9.3
#  - 1.9.2        # Fails to install concord gem (required by nokogiri)
#  - jruby-19mode # Fails to install sqlite3
#  - rbx-19mode
#  - ruby-head    # Fails to download rubygems.org/latest_specs.4.8.gz
#  - jruby-head   # Fails to install sqlite3
